name = "RobustOptimization"
uuid = "1ea8c22c-f78a-4936-8625-1fcff2c9b5dd"
authors = ["Michael Hartisch", "Tom Klein"]
version = "0.1.0"

[deps]
Coverage = "a2441757-f6aa-5fb2-8edb-039e3f45d037"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
MathOptInterface = "b8f27783-ece8-5eb3-8dc8-9495eed66fee"
[compat]
Coverage = "1"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
